import type { Permission, Role } from "@/types";

export const permissionLabels: Record<Permission, string> = {
  "auth:manage": "Manage users and roles",
  "billing:read": "View billing",
  "billing:manage": "Manage billing controls",
  "utility:read": "View utilities",
  "utility:manage": "Manage utility charges",
  "penalty:read": "View penalties",
  "penalty:manage": "Issue and manage penalties",
  "vendor:read": "View vendors",
  "vendor:review": "Review vendor applications",
  "coordination:read": "View coordination",
  "coordination:write": "Post coordination updates",
  "resource:read": "View resource requests",
  "resource:create": "Create resource requests",
  "resource:review": "Review resource requests",
  "stall:read": "View stalls",
  "stall:write": "Manage stalls",
  "booking:read": "View bookings",
  "booking:create": "Create bookings",
  "booking:update": "Review bookings",
  "payment:read": "View payments",
  "payment:create": "Create payments",
  "notification:read": "View notifications",
  "notification:update": "Update notifications",
  "announcement:read": "View announcements",
  "announcement:write": "Publish announcements",
  "ticket:read": "View complaints",
  "ticket:create": "Create complaints",
  "ticket:update": "Update complaints",
  "report:read": "Generate reports",
  "audit:read": "View audit trail",
  "fallback:query": "Use fallback assistant",
};

export const rolePermissionMatrix: Record<Role, Permission[]> = {
  vendor: [
    "stall:read",
    "booking:read",
    "booking:create",
    "payment:read",
    "payment:create",
    "utility:read",
    "penalty:read",
    "notification:read",
    "notification:update",
    "announcement:read",
    "ticket:read",
    "ticket:create",
  ],
  manager: [
    "billing:read",
    "utility:read",
    "utility:manage",
    "penalty:read",
    "vendor:read",
    "vendor:review",
    "coordination:read",
    "coordination:write",
    "resource:read",
    "resource:create",
    "stall:read",
    "stall:write",
    "booking:read",
    "booking:update",
    "payment:read",
    "notification:read",
    "announcement:read",
    "announcement:write",
    "ticket:read",
    "ticket:update",
    "report:read",
    "audit:read",
  ],
  official: [
    "billing:read",
    "utility:read",
    "penalty:read",
    "penalty:manage",
    "coordination:read",
    "coordination:write",
    "resource:read",
    "resource:review",
    "stall:read",
    "booking:read",
    "payment:read",
    "announcement:read",
    "announcement:write",
    "ticket:read",
    "report:read",
    "audit:read",
    "vendor:read",
  ],
  admin: [
    "auth:manage",
    "billing:read",
    "billing:manage",
    "utility:read",
    "utility:manage",
    "penalty:read",
    "penalty:manage",
    "vendor:read",
    "coordination:read",
    "coordination:write",
    "resource:read",
    "resource:review",
    "stall:read",
    "booking:read",
    "payment:read",
    "notification:read",
    "announcement:read",
    "announcement:write",
    "ticket:read",
    "report:read",
    "audit:read",
  ],
};

export const permissionGroups: Array<{ title: string; permissions: Permission[] }> = [
  {
    title: "Access",
    permissions: ["auth:manage", "audit:read", "report:read"],
  },
  {
    title: "Operations",
    permissions: ["vendor:read", "vendor:review", "stall:read", "stall:write", "booking:read", "booking:create", "booking:update"],
  },
  {
    title: "Financial",
    permissions: ["billing:read", "billing:manage", "payment:read", "payment:create", "utility:read", "utility:manage", "penalty:read", "penalty:manage"],
  },
  {
    title: "Workflow",
    permissions: ["ticket:read", "ticket:create", "ticket:update", "announcement:read", "announcement:write", "coordination:read", "coordination:write", "resource:read", "resource:create", "resource:review"],
  },
  {
    title: "System",
    permissions: ["notification:read", "notification:update", "fallback:query"],
  },
];
